#%RAML 1.0
baseUri: https://mocksvc.mulesoft.com/mocks/fcaf1de9-a1b4-47c1-98f7-6c7586b21e73 # 
title: db_test
/user:
  get:
    responses: 
      200:
        body: 
          application/json:
            example: |
             {"name":"pavan"}